spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 38064462376-bbf8mcm312ulv7sad4ksqsdcieu4lq3c.apps.googleusercontent.com
            client-secret: ${client-secret}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
